### ISSUE TITLE
make the video server less complex

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/server#1]
Right now the [video server](https://github.com/wm-robo-ops/server/blob/master/video_server.js) introduces unnecessary complexity by requiring a password and some other parameters. We should remove that and simplify it as much as possible.

@ajwells thoughts?

**Comment by ajwells** [comment]
Probably don't need password but we should leave in the other two params for now to see if we want to change resolution. Would should to test the best sizes we can get from the pis and on the mobile router to make the best decision. Could even vary that as args if we want to
