### ISSUE TITLE
standardize server design

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/server#2]
We have a lot of servers and they are all unique in their own special way. We use a bunch of different libraries like `express`, `http`, `net`, `ws`, `websocket`, etc.

We should pick a standard way and stick to it.

/cc @ajwells

**Comment by ajwells** [comment]
we definitely need at least net and ws not sure what the difference between ws and websocket. Also for video streaming we may need to just keep that as a http server as we have that working now how it is

**Comment by kelvinabrokwa** [comment]
the server is fine as it
