### ISSUE TITLE
dashboard on off

### ISSUE THREAD

**Issue by ajwells** [wm-robo-ops/server#6]
all video toggles turn on/off BigDaddy main

**Comment by kelvinabrokwa** [comment]
@ajwells yeah this was because of placeholder code since we don't have the other pi IP addresses -> https://github.com/wm-robo-ops/server/blob/38107eb914ed14024d436320a420648fe9760ae9/server.js#L127

**Comment by kelvinabrokwa** [comment]
done in https://github.com/wm-robo-ops/server/commit/22fce9c35c920ffd97ce159484db11405483bda9
